services:
  - type: web
    name: vidur-course-ml
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true